name: Quality Gate

on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unit Tests and Coverage
        uses: ./.github/actions/docker-build-gcc
